### ISSUE TITLE
Bot generation error xmas equipment

### ISSUE THREAD

**Issue by crankedguy** [dwesterwick/SPTQuestingBots#27]
Hi, 

I had the following bot generation error, the problem was it made the client hang for a very long time which made me nearly quitting the game. Eventually it resolved itself, so I do not know if it is worth to investigate further or if you can accelerate the hangup. Just wanted to mention it. Was 0.6.1 alpha version.

Cheers

```
Unable to remove christmas equipment from slot: Headwear as it cannot be found on bot: sptBear
TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at SeasonalEventService.removeChristmasItemsFromBotInventory (C:\snapshot\src\services\SeasonalEventService.ts:286:24)
    at BotGen.myGenerateBot (H:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_gen.ts:358:43)
    at BotGen.myPrepareAndGenerateBot (H:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_gen.ts:326:20)
    at BotGenerator.prepareAndGenerateBot (H:\Games\SPT\user\mods\SPT-Realism\src\mod.ts:175:35)
    at BotController.returnSingleBotFromCache (C:\snapshot\src\controllers\BotController.ts:339:54)
    at BotController.generate (C:\snapshot\src\controllers\BotController.ts:191:21)
    at QuestingBots.generateBots (H:\Games\SPT\user\mods\DanW-SPTQuestingBots\src\mod.ts:505:41)
    at Object.action (H:\Games\SPT\user\mods\DanW-SPTQuestingBots\src\mod.ts:152:39)
    at DynamicRouterMod.handleDynamic (C:\snapshot\src\di\Router.ts:65:59)
TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at SeasonalEventService.removeChristmasItemsFromBotInventory (C:\snapshot\src\services\SeasonalEventService.ts:286:24)
    at BotGen.myGenerateBot (H:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_gen.ts:358:43)
    at BotGen.myPrepareAndGenerateBot (H:\Games\SPT\user\mods\SPT-Realism\src\bots\bot_gen.ts:326:20)
    at BotGenerator.prepareAndGenerateBot (H:\Games\SPT\user\mods\SPT-Realism\src\mod.ts:175:35)
    at BotController.returnSingleBotFromCache (C:\snapshot\src\controllers\BotController.ts:339:54)
    at BotController.generate (C:\snapshot\src\controllers\BotController.ts:191:21)
    at QuestingBots.generateBots (H:\Games\SPT\user\mods\DanW-SPTQuestingBots\src\mod.ts:505:41)
    at Object.action (H:\Games\SPT\user\mods\DanW-SPTQuestingBots\src\mod.ts:152:39)
    at DynamicRouterMod.handleDynamic (C:\snapshot\src\di\Router.ts:65:59)
```

**Comment by dwesterwick** [comment]
Questing Bots reroutes bot-generation requests, but it doesn't perform them. Anything downstream of the endpoint is controlled by SPT or other mods.
